title: "Induja Shankar"
email: induja.shankar@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Ooof! LHD IS FUN!
baseurl: "/" 
url: "/portfolio-template" 
twitter_username: indujashankar
github_username:  indujaaaa

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
